import './globals.css'
import type { Metadata } from 'next'
import Header from './header'
import Footer from './footer'
import { Suspense } from 'react'
import Loading from './loading'

export const metadata: Metadata = {
  title: 'Next13 App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className='mx-auto bg-slate-500'>
        <div className='flex flex-col min-h-screen pt-16'>
          <Header />
          <main className='flex-grow'>
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
